'use server';
/**
 * @fileOverview An AI flow to detect if an image is AI-generated.
 *
 * - detectAiImage - A function that handles the AI image detection process.
 * - DetectAiImageInput - The input type for the detectAiImage function.
 * - DetectAiImageOutput - The return type for the detectAiImage function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const DetectAiImageInputSchema = z.object({
  photoDataUri: z
    .string()
    .describe(
      "A photo, as a data URI that must include a MIME type and use Base64 encoding. Expected format: 'data:<mimetype>;base64,<encoded_data>'."
    ),
});
export type DetectAiImageInput = z.infer<typeof DetectAiImageInputSchema>;

const DetectAiImageOutputSchema = z.object({
  isAiGenerated: z.boolean().describe('Whether or not the image is determined to be AI-generated.'),
  reasoning: z.string().describe('The reasoning behind the determination.'),
});
export type DetectAiImageOutput = z.infer<typeof DetectAiImageOutputSchema>;

export async function detectAiImage(
  input: DetectAiImageInput
): Promise<DetectAiImageOutput> {
  return detectAiImageFlow(input);
}

const prompt = ai.definePrompt({
  name: 'detectAiImagePrompt',
  input: {schema: DetectAiImageInputSchema},
  output: {schema: DetectAiImageOutputSchema},
  prompt: `You are an expert at detecting AI-generated images. Analyze the following image.

Determine if the image provided is a real photograph or if it has been generated by an AI model.

- If the image IS AI-generated, set isAiGenerated to true.
- If the image is a real photograph, set isAiGenerated to false.

Provide your reasoning.

Image: {{media url=photoDataUri}}`,
});

const detectAiImageFlow = ai.defineFlow(
  {
    name: 'detectAiImageFlow',
    inputSchema: DetectAiImageInputSchema,
    outputSchema: DetectAiImageOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
